# Python stubs generated by omniidl from WordyApp.idl
# DO NOT EDIT THIS FILE!

import omniORB, _omnipy
from omniORB import CORBA, PortableServer
_0_CORBA = CORBA


_omnipy.checkVersion(4,2, __file__, 1)

try:
    property
except NameError:
    def property(*args):
        return None


#
# Start of module "WordyApp"
#
__name__ = "WordyApp"
_0_WordyApp = omniORB.openModule("WordyApp", r"WordyApp.idl")
_0_WordyApp__POA = omniORB.openModule("WordyApp__POA", r"WordyApp.idl")


# exception InvalidCredentials
_0_WordyApp.InvalidCredentials = omniORB.newEmptyClass()
class InvalidCredentials (CORBA.UserException):
    _NP_RepositoryId = "IDL:WordyApp/InvalidCredentials:1.0"

    def __init__(self, message):
        CORBA.UserException.__init__(self, message)
        self.message = message

_0_WordyApp.InvalidCredentials = InvalidCredentials
_0_WordyApp._d_InvalidCredentials  = (omniORB.tcInternal.tv_except, InvalidCredentials, InvalidCredentials._NP_RepositoryId, "InvalidCredentials", "message", (omniORB.tcInternal.tv_string,0))
_0_WordyApp._tc_InvalidCredentials = omniORB.tcInternal.createTypeCode(_0_WordyApp._d_InvalidCredentials)
omniORB.registerType(InvalidCredentials._NP_RepositoryId, _0_WordyApp._d_InvalidCredentials, _0_WordyApp._tc_InvalidCredentials)
del InvalidCredentials

# exception UserActive
_0_WordyApp.UserActive = omniORB.newEmptyClass()
class UserActive (CORBA.UserException):
    _NP_RepositoryId = "IDL:WordyApp/UserActive:1.0"

    def __init__(self, message):
        CORBA.UserException.__init__(self, message)
        self.message = message

_0_WordyApp.UserActive = UserActive
_0_WordyApp._d_UserActive  = (omniORB.tcInternal.tv_except, UserActive, UserActive._NP_RepositoryId, "UserActive", "message", (omniORB.tcInternal.tv_string,0))
_0_WordyApp._tc_UserActive = omniORB.tcInternal.createTypeCode(_0_WordyApp._d_UserActive)
omniORB.registerType(UserActive._NP_RepositoryId, _0_WordyApp._d_UserActive, _0_WordyApp._tc_UserActive)
del UserActive

# typedef ... array
class array:
    _NP_RepositoryId = "IDL:WordyApp/array:1.0"
    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")
_0_WordyApp.array = array
_0_WordyApp._d_array  = (omniORB.tcInternal.tv_sequence, (omniORB.tcInternal.tv_string,0), 0)
_0_WordyApp._ad_array = (omniORB.tcInternal.tv_alias, array._NP_RepositoryId, "array", (omniORB.tcInternal.tv_sequence, (omniORB.tcInternal.tv_string,0), 0))
_0_WordyApp._tc_array = omniORB.tcInternal.createTypeCode(_0_WordyApp._ad_array)
omniORB.registerType(array._NP_RepositoryId, _0_WordyApp._ad_array, _0_WordyApp._tc_array)
del array

# interface WordyGame
_0_WordyApp._d_WordyGame = (omniORB.tcInternal.tv_objref, "IDL:WordyApp/WordyGame:1.0", "WordyGame")
omniORB.typeMapping["IDL:WordyApp/WordyGame:1.0"] = _0_WordyApp._d_WordyGame
_0_WordyApp.WordyGame = omniORB.newEmptyClass()
class WordyGame :
    _NP_RepositoryId = _0_WordyApp._d_WordyGame[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil


_0_WordyApp.WordyGame = WordyGame
_0_WordyApp._tc_WordyGame = omniORB.tcInternal.createTypeCode(_0_WordyApp._d_WordyGame)
omniORB.registerType(WordyGame._NP_RepositoryId, _0_WordyApp._d_WordyGame, _0_WordyApp._tc_WordyGame)

# WordyGame operations and attributes
WordyGame._d_login = (((omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0)), (), {_0_WordyApp.InvalidCredentials._NP_RepositoryId: _0_WordyApp._d_InvalidCredentials, _0_WordyApp.UserActive._NP_RepositoryId: _0_WordyApp._d_UserActive})
WordyGame._d_logout = (((omniORB.tcInternal.tv_string,0), ), (), None)
WordyGame._d_register = (((omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0)), (omniORB.tcInternal.tv_boolean, ), None)
WordyGame._d_getFiveLongestWords = ((), (omniORB.typeMapping["IDL:WordyApp/array:1.0"], ), None)
WordyGame._d_getTopFivePlayers = ((), (omniORB.typeMapping["IDL:WordyApp/array:1.0"], ), None)
WordyGame._d_startNewWaitingRoom = ((), (), None)
WordyGame._d_joinWaitingRoom = (((omniORB.tcInternal.tv_string,0), ), (omniORB.tcInternal.tv_boolean, ), None)
WordyGame._d_leaveGameRoom = (((omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0)), (), None)
WordyGame._d_getWaitingRoomInformation = ((), (omniORB.typeMapping["IDL:WordyApp/array:1.0"], ), None)
WordyGame._d_submitWord = (((omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0), omniORB.tcInternal.tv_long, (omniORB.tcInternal.tv_string,0)), (omniORB.tcInternal.tv_boolean, ), None)
WordyGame._d_endRound = (((omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0)), (omniORB.tcInternal.tv_boolean, ), None)
WordyGame._d_getGameRoomInformation = (((omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0)), (omniORB.typeMapping["IDL:WordyApp/array:1.0"], ), None)

# WordyGame object reference
class _objref_WordyGame (CORBA.Object):
    _NP_RepositoryId = WordyGame._NP_RepositoryId

    def __init__(self, obj):
        CORBA.Object.__init__(self, obj)

    def login(self, *args):
        return self._obj.invoke("login", _0_WordyApp.WordyGame._d_login, args)

    def logout(self, *args):
        return self._obj.invoke("logout", _0_WordyApp.WordyGame._d_logout, args)

    def register(self, *args):
        return self._obj.invoke("register", _0_WordyApp.WordyGame._d_register, args)

    def getFiveLongestWords(self, *args):
        return self._obj.invoke("getFiveLongestWords", _0_WordyApp.WordyGame._d_getFiveLongestWords, args)

    def getTopFivePlayers(self, *args):
        return self._obj.invoke("getTopFivePlayers", _0_WordyApp.WordyGame._d_getTopFivePlayers, args)

    def startNewWaitingRoom(self, *args):
        return self._obj.invoke("startNewWaitingRoom", _0_WordyApp.WordyGame._d_startNewWaitingRoom, args)

    def joinWaitingRoom(self, *args):
        return self._obj.invoke("joinWaitingRoom", _0_WordyApp.WordyGame._d_joinWaitingRoom, args)

    def leaveGameRoom(self, *args):
        return self._obj.invoke("leaveGameRoom", _0_WordyApp.WordyGame._d_leaveGameRoom, args)

    def getWaitingRoomInformation(self, *args):
        return self._obj.invoke("getWaitingRoomInformation", _0_WordyApp.WordyGame._d_getWaitingRoomInformation, args)

    def submitWord(self, *args):
        return self._obj.invoke("submitWord", _0_WordyApp.WordyGame._d_submitWord, args)

    def endRound(self, *args):
        return self._obj.invoke("endRound", _0_WordyApp.WordyGame._d_endRound, args)

    def getGameRoomInformation(self, *args):
        return self._obj.invoke("getGameRoomInformation", _0_WordyApp.WordyGame._d_getGameRoomInformation, args)

omniORB.registerObjref(WordyGame._NP_RepositoryId, _objref_WordyGame)
_0_WordyApp._objref_WordyGame = _objref_WordyGame
del WordyGame, _objref_WordyGame

# WordyGame skeleton
__name__ = "WordyApp__POA"
class WordyGame (PortableServer.Servant):
    _NP_RepositoryId = _0_WordyApp.WordyGame._NP_RepositoryId


    _omni_op_d = {"login": _0_WordyApp.WordyGame._d_login, "logout": _0_WordyApp.WordyGame._d_logout, "register": _0_WordyApp.WordyGame._d_register, "getFiveLongestWords": _0_WordyApp.WordyGame._d_getFiveLongestWords, "getTopFivePlayers": _0_WordyApp.WordyGame._d_getTopFivePlayers, "startNewWaitingRoom": _0_WordyApp.WordyGame._d_startNewWaitingRoom, "joinWaitingRoom": _0_WordyApp.WordyGame._d_joinWaitingRoom, "leaveGameRoom": _0_WordyApp.WordyGame._d_leaveGameRoom, "getWaitingRoomInformation": _0_WordyApp.WordyGame._d_getWaitingRoomInformation, "submitWord": _0_WordyApp.WordyGame._d_submitWord, "endRound": _0_WordyApp.WordyGame._d_endRound, "getGameRoomInformation": _0_WordyApp.WordyGame._d_getGameRoomInformation}

WordyGame._omni_skeleton = WordyGame
_0_WordyApp__POA.WordyGame = WordyGame
omniORB.registerSkeleton(WordyGame._NP_RepositoryId, WordyGame)
del WordyGame
__name__ = "WordyApp"

#
# End of module "WordyApp"
#
__name__ = "WordyApp_idl"

_exported_modules = ( "WordyApp", )

# The end.
