package Server_Java.WordyApp;


/**
* WordyApp/InvalidCredentials.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WordyApp.idl
* Sunday, May 28, 2023 11:06:09 PM SGT
*/

public final class InvalidCredentials extends org.omg.CORBA.UserException
{
  public String message = null;

  public InvalidCredentials ()
  {
    super(InvalidCredentialsHelper.id());
  } // ctor

  public InvalidCredentials (String _message)
  {
    super(InvalidCredentialsHelper.id());
    message = _message;
  } // ctor


  public InvalidCredentials (String $reason, String _message)
  {
    super(InvalidCredentialsHelper.id() + "  " + $reason);
    message = _message;
  } // ctor

} // class InvalidCredentials
