package Server_Java.WordyApp;

/**
* WordyApp/UserActiveHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WordyApp.idl
* Sunday, May 28, 2023 11:06:09 PM SGT
*/

public final class UserActiveHolder implements org.omg.CORBA.portable.Streamable
{
  public UserActive value = null;

  public UserActiveHolder ()
  {
  }

  public UserActiveHolder (UserActive initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = UserActiveHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    UserActiveHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return UserActiveHelper.type ();
  }

}
