package Server_Java.WordyApp;


/**
* WordyApp/UserActive.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WordyApp.idl
* Sunday, May 28, 2023 11:06:09 PM SGT
*/

public final class UserActive extends org.omg.CORBA.UserException
{
  public String message = null;

  public UserActive ()
  {
    super(UserActiveHelper.id());
  } // ctor

  public UserActive (String _message)
  {
    super(UserActiveHelper.id());
    message = _message;
  } // ctor


  public UserActive (String $reason, String _message)
  {
    super(UserActiveHelper.id() + "  " + $reason);
    message = _message;
  } // ctor

} // class UserActive
