package Server_Java.WordyApp;


/**
* WordyApp/WordyGame.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WordyApp.idl
* Sunday, May 28, 2023 11:06:09 PM SGT
*/

public interface WordyGame extends WordyGameOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity
{
} // interface WordyGame
