package Server_Java.WordyApp;


/**
* WordyApp/WordyGamePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WordyApp.idl
* Sunday, May 28, 2023 11:06:09 PM SGT
*/

public abstract class WordyGamePOA extends org.omg.PortableServer.Servant
 implements WordyGameOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("login", new Integer (0));
    _methods.put ("logout", new Integer (1));
    _methods.put ("register", new Integer (2));
    _methods.put ("getFiveLongestWords", new Integer (3));
    _methods.put ("getTopFivePlayers", new Integer (4));
    _methods.put ("startNewWaitingRoom", new Integer (5));
    _methods.put ("joinWaitingRoom", new Integer (6));
    _methods.put ("leaveGameRoom", new Integer (7));
    _methods.put ("getWaitingRoomInformation", new Integer (8));
    _methods.put ("submitWord", new Integer (9));
    _methods.put ("endRound", new Integer (10));
    _methods.put ("getGameRoomInformation", new Integer (11));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    Integer __method = (Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // WordyApp/WordyGame/login
       {
         try {
           String username = in.read_string ();
           String password = in.read_string ();
           this.login (username, password);
           out = $rh.createReply();
         } catch (InvalidCredentials $ex) {
           out = $rh.createExceptionReply ();
           InvalidCredentialsHelper.write (out, $ex);
         } catch (UserActive $ex) {
           out = $rh.createExceptionReply ();
           UserActiveHelper.write (out, $ex);
         }
         break;
       }

       case 1:  // WordyApp/WordyGame/logout
       {
         String username = in.read_string ();
         this.logout (username);
         out = $rh.createReply();
         break;
       }

       case 2:  // WordyApp/WordyGame/register
       {
         String username = in.read_string ();
         String password = in.read_string ();
         boolean $result = false;
         $result = this.register (username, password);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 3:  // WordyApp/WordyGame/getFiveLongestWords
       {
         String $result[] = null;
         $result = this.getFiveLongestWords ();
         out = $rh.createReply();
         arrayHelper.write (out, $result);
         break;
       }

       case 4:  // WordyApp/WordyGame/getTopFivePlayers
       {
         String $result[] = null;
         $result = this.getTopFivePlayers ();
         out = $rh.createReply();
         arrayHelper.write (out, $result);
         break;
       }

       case 5:  // WordyApp/WordyGame/startNewWaitingRoom
       {
         this.startNewWaitingRoom ();
         out = $rh.createReply();
         break;
       }

       case 6:  // WordyApp/WordyGame/joinWaitingRoom
       {
         String username = in.read_string ();
         boolean $result = false;
         $result = this.joinWaitingRoom (username);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 7:  // WordyApp/WordyGame/leaveGameRoom
       {
         String username = in.read_string ();
         String roomName = in.read_string ();
         this.leaveGameRoom (username, roomName);
         out = $rh.createReply();
         break;
       }

       case 8:  // WordyApp/WordyGame/getWaitingRoomInformation
       {
         String $result[] = null;
         $result = this.getWaitingRoomInformation ();
         out = $rh.createReply();
         arrayHelper.write (out, $result);
         break;
       }

       case 9:  // WordyApp/WordyGame/submitWord
       {
         String inputString = in.read_string ();
         String username = in.read_string ();
         int roundNumber = in.read_long ();
         String roomName = in.read_string ();
         boolean $result = false;
         $result = this.submitWord (inputString, username, roundNumber, roomName);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 10:  // WordyApp/WordyGame/endRound
       {
         String username = in.read_string ();
         String roomName = in.read_string ();
         boolean $result = false;
         $result = this.endRound (username, roomName);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 11:  // WordyApp/WordyGame/getGameRoomInformation
       {
         String roomName = in.read_string ();
         String username = in.read_string ();
         String $result[] = null;
         $result = this.getGameRoomInformation (roomName, username);
         out = $rh.createReply();
         arrayHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:WordyApp/WordyGame:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public WordyGame _this()
  {
    return WordyGameHelper.narrow(
    super._this_object());
  }

  public WordyGame _this(org.omg.CORBA.ORB orb)
  {
    return WordyGameHelper.narrow(
    super._this_object(orb));
  }


} // class WordyGamePOA
